version: "3.8"

services:
  rolling_bites:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DATABASE}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
